### ISSUE TITLE
Docker environment variable AD_FILENAME_TEMPLATE not working

### ISSUE THREAD

**Issue by tweingart89** [jamesridgway/attachment-downloader#58]
Hi,

I start a docker container with docker-compose.
Setting the environment variable AD_FILENAME_TEMPLATE has no effect. It seems that my defined value is not accepted. Apparently only the default value {{ attachment_name }} is used. What am I doing wrong?
Attached is my docker-compose file.

```
version: '3.3'

services:
  attachment-downloader:
    image: jantek/attachment-downloader:1.2.7
    environment:
      AD_HOST: imap.domain.local
      AD_USERNAME: someuser@domain.loacl
      AD_PASSWORD: somepass
      AD_IMAP_FOLDER: INBOX
      AD_PORT: 993
      AD_DOWNLOAD_FOLDER: /output
      AD_INTERVAL: 10
      AD_DELETE: 1
      AD_DELETE_COPY_FOLDER: INBOX/ARCHIVE
      AD_FILENAME_TEMPLATE: '{{ "{{date}} {{ message_id }} {{ attachment_name }}" }}'
      AD_LOGLEVEL: DEBUG
    volumes:
      - /data/output:/output
```
